### ISSUE TITLE
指定のファイルだけを package に含むようにしたい

### ISSUE THREAD

**Issue by keisukesaito7** [keisukesaito7/ruby-node-test#2]
## やりたい

1 つの関数に必要なファイルだけを含むようにしたい。

### 試す

- 全部 exclude する
- 関数ごとに必要なファイルを include

https://forum.serverless.com/t/how-to-ignore-directories-and-files-for-a-deployment/2624/3

```yml
package:
  individually: true
  exclude:
    - ".*/**"

functions:
  hello:
    handler: handler.hello
    description: Simple Hello, World
    package:
      include:
        - handler.rb
  httparty:
    handler: libs/httparty.hello
    description: Use Gem
    package:
      include:
        - libs/httparty.rb
```

### 結果

全ファイルが含まれてしまった。
